config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"
  resources "books"
  resources "users"
  resources "genres"
  resources "activities", only: :index
  get "/:page" => "pages#show"
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :book_genres, dependent: :destroy
  has_many :books, through: :book_genres

  alias_attribute :pub_act_key, :name
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: %i[ show edit update destroy ]

  def index
    @pagy, @genres = pagy(:offset, Genre.kept.all.order(name: :asc))
    @genres_total = Genre.kept.all.count
  end

  def show
    @pagy, @books = pagy(:offset, @genre.books.order(title: :asc))

    activities = @genre.activities
    @activities = activities.order(created_at: :desc)
  end

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: "Genre was successfully created." }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entry }
      end
    end
  end

  def edit
  end

  def update
    if @genre.update(genre_params)
      redirect_to @genre
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @genre.discard
    redirect_to genres_path, notice: "Genre destroyed"
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_book.html.erb
<tr id="<%= dom_id book %>">
  <td><%= link_to book.title, book %></td>
  <td><%= book.short_description %></td>
  <td><%= book.genres.map{|bg| link_to bg.name, bg}.join(', ').html_safe %></td>
  <td><%= link_to book.user.inverted_full_name, book.user %></td>
</tr>

app/views/genres/_form.html.erb
<%= form_with model: @genre do |form| %>
  <div class="mb-4">
    <%= form.label :name, class: "form-label fw-bold" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="d-flex flex-row justify-content-end align-items-center gap-2">
    <%= link_to "Cancel", genres_path, class: "btn btn-danger" %>
    |
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/genres/_genre.html.erb
<tr id="<%= dom_id genre %>">
  <td><%= link_to genre.name, genre %></td>
  <td><%= genre.books.count %></td>
  <td>
    <div class="d-flex flex-row justify-content-end align-items-center gap-1">
      <%= link_to edit_genre_path(genre), class: "btn btn-primary" do %>
        <i class="fa-solid fa-pen-to-square"></i>
      <% end %>
      <%= button_to genre, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger" do %>
        <i class="fa-solid fa-trash"></i>
      <% end %>
    </div>
  </td>
</tr>

app/views/genres/edit.html.erb
<h2 class="mb-4">Edit Genre</h2>
<%= link_to "Back", genres_path, class: "btn btn-primary" %>
<hr>
<%= render 'form' %>

app/views/genres/index.html.erb
<h1 class="mb-4">Genres (<%= @genres_total %>)</h1>
<%= link_to "Add a genre", new_genre_path, class: "btn btn-primary" %>
<hr>
<% if @genres.present? %>
  <table class="table table-striped text-start">
    <thead>
      <th scope="col">Name</th>
      <th scope="col">No. of books</th>
      <th scope="col"></th>
    </thead>
    <tbody>
      <%= render @genres %>
    </tbody>
  </table>
  <div class="d-flex justify-content-end">
    <%== @pagy.series_nav(:bootstrap) %>
  </div>
<% end %>

app/views/genres/new.html.erb
<h2 class="mb-4">New Genre</h2>
<%= link_to "Back", genres_path, class: "btn btn-primary" %>
<hr>
<%= render 'form' %>

app/views/genres/show.html.erb
<h6 class="fw-lighter">GENRE</h6>
<h2><%= @genre.name %></h2>
<p class="mb-4">Number of books: <%= @genre.books.count %></p>
<div class="d-flex flex-row justify-content-start align-items-center gap-1">
  <%= link_to 'Back to genres', genres_path, class: "btn btn-primary" %>
  <%= link_to edit_genre_path(@genre), class: "btn btn-primary" do %>
    <i class="fa-solid fa-pen-to-square"></i>
  <% end %>
  <%= button_to @genre, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn btn-danger" do %>
    <i class="fa-solid fa-trash"></i>
  <% end %>
</div>
<hr>
<% if @books.present? %>
  <h3>Books</h3>
  <table class="table table-striped text-start">
    <thead>
        <th scope="col">Name</th>
        <th scope="col">Short Description</th>
        <th scope="col">Genre</th>
        <th scope="col">Owner</th>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr id="<%= dom_id book %>">
          <td><%= link_to book.title, book %></td>
          <td><%= book.short_description %></td>
          <td><%= book.genres.map{|bg| link_to bg.name, bg}.join(', ').html_safe %></td>
          <td><%= link_to book.user.inverted_full_name, book.user %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-end">
    <%== @pagy.series_nav(:bootstrap) %>
  </div>
<% end %>
<hr>
<h3>History</h3>
<table class="table table-striped text-start">
  <thead>
    <th scope="col">Activity</th>
    <th scope="col">Timestamp</th>
  </thead>
  <tbody>
    <%= render_activities(@activities, {layout: :activity}) %>
  </tbody>
</table>