config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "books#index"
  resources "books"
  resources "users"
  resources "genres"
  resources "activities", only: :index
  get "/:page" => "pages#show"
end

app/views/layouts/components/_nav.html.erb
<nav class="navbar navbar-expand navbar-light bg-light p-3">
  <div class="d-flex flex-row justify-content-between align-items-center w-100">
    <div class="navbar-brand fw-bolder" href="#">BOOKS (KP Training)</div>
    <ul class="navbar-nav">
      <% if authenticated? %>
        <li class="nav-item">
          <%= link_to "Library", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Genres", genres_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Activity", activities_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <a href="/terms" class="nav-link">Terms</a>
      </li>
      <li class="nav-item">
        <a href="/privacy" class="nav-link">Privacy</a>
      </li>
      <% if authenticated? %>
        <li class="nav-item d-flex justify-content-center align-items-center">
          <%= button_to session_path, method: :delete, class: "nav-link" do %>
            <i class="fa-solid fa-arrow-right-to-bracket"></i>
          <% end %>
        </li>
      <% else %>
        <%= link_to "Log In", new_session_path, class: "nav-link fw-bolder" %>
      <% end %>
    </ul>
  </div>
</nav>